"""Fig. 2 of the ACIIDS 2027 paper, from analysis/gl_results.json (generated by
analysis/gl_results.py from the runs on exp/eval-input-diagnostic).
Run: .venv/bin/python paper/aciids2027/figures/make_figures.py

Palette checked with the dataviz validator (blue/orange pass CVD and normal-vision
separation); the Multi-Token references are grey with a second encoding (dashes,
hollow bars) and direct labels, so they never rely on colour alone."""
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

OUT = Path(__file__).parent
D = json.loads((OUT.parent / "analysis" / "gl_results.json").read_text())
plt.rcParams.update({"font.family": "serif", "font.size": 8, "axes.spines.top": False,
                     "axes.spines.right": False, "pdf.fonttype": 42})
BLUE, ORANGE, GREY, INK = "#2a6fb0", "#c96a1c", "#6b7078", "#333333"
MT8, MT8_LORA = 50.74, 54.78           # Multi-Token 8, val F1: bridge only (4 seeds), + LoRA 3 ep (3 seeds)

fig, (a, b) = plt.subplots(1, 2, figsize=(6.8, 2.6), gridspec_kw={"width_ratios": [1.15, 1]})

# (a) val F1 against the number of visual tokens (g + k), log scale
for g, colour in ((8, ORANGE), (14, BLUE)):
    pts = [D["configs"][f"g{g}-k{k}"] for k in (1, 9, 36, 144)]
    xs = [p["tokens"] for p in pts]
    ys = [p["val"]["f1"][0] for p in pts]
    sd = [p["val"]["f1"][1] for p in pts]
    a.errorbar(xs, ys, yerr=sd, color=colour, lw=1.6, marker="o", ms=4, capsize=1.5,
               elinewidth=0.6, label=f"$g={g}$ global + $k$ local")
    for x, y, k in zip(xs, ys, (1, 9, 36, 144)):
        if g == 14:
            a.annotate(f"$k$={k}", (x, y), textcoords="offset points", xytext=(4, -9),
                       fontsize=6, color=BLUE, ha="left")
a.axhline(MT8, color=GREY, lw=0.9, ls=(0, (4, 2)))
a.text(160, MT8 - 0.15, "Multi-Token 8 (global only)", fontsize=6, color=INK, va="top", ha="right")
a.axhline(MT8_LORA, color=GREY, lw=0.9, ls=(0, (1, 1.5)))
a.text(8.3, MT8_LORA + 0.12, "Multi-Token 8 + LoRA (3 ep)", fontsize=6, color=INK, va="bottom")
knee = D["configs"]["g14-k36"]          # circled; named in the caption
a.scatter([knee["tokens"]], [knee["val"]["f1"][0]], s=70, facecolors="none", edgecolors=INK, lw=0.9, zorder=5)
a.set_xscale("log")
a.set_xticks([8, 15, 23, 50, 158]); a.set_xticklabels(["8", "15", "23", "50", "158"])
a.set_xlabel("visual tokens to the decoder ($g+k$, log scale)")
a.set_ylabel("F1 (val)")
a.set_ylim(49.5, 57.5)
a.legend(frameon=False, fontsize=6.5, loc="upper left")
a.set_title("(a) Accuracy against visual tokens", fontsize=8)

# (b) val F1 by reasoning type
P = D["per_category_val_f1"]
order = sorted(P["g14-k36"], key=lambda c: -P["g14-k36"][c]["n"])
label = {"yesno": "yes/no"}
y = list(range(len(order)))[::-1]
h = 0.27
for off, key, kw, lab in (
        (+h, "multi_token_s42", dict(facecolor="white", edgecolor=GREY, lw=0.8), "Multi-Token 8"),
        (0.0, "multi_token_lora3ep_s42", dict(color=ORANGE), "Multi-Token 8 + LoRA (3 ep)"),
        (-h, "g14-k36", dict(color=BLUE), "ours, $g$=14, $k$=36")):
    b.barh([k + off for k in y], [P[key][c]["f1"] for c in order], h, label=lab, **kw)
for k, c in zip(y, order):
    gain = P["g14-k36"][c]["f1"] - P["multi_token_s42"][c]["f1"]
    top = max(P[key][c]["f1"] for key in ("multi_token_s42", "multi_token_lora3ep_s42", "g14-k36"))
    b.text(top + 0.6, k - h, f"{gain:+.1f}", va="center", fontsize=6, color=INK)
b.set_yticks(y)
b.set_yticklabels([f"{label.get(c, c)} ({P['g14-k36'][c]['n']})" for c in order], fontsize=6.5)
b.set_xlim(30, 76); b.set_xlabel("F1 (val)")
b.legend(frameon=False, fontsize=6, loc="upper center", bbox_to_anchor=(0.42, -0.2), ncol=3)
b.set_title("(b) By reasoning type (gain of ours over Multi-Token 8)", fontsize=8)

fig.tight_layout(w_pad=1.5)
fig.savefig(OUT / "fig_results.pdf", bbox_inches="tight")
fig.savefig(OUT / "fig_results.png", dpi=200, bbox_inches="tight")
print("wrote", OUT / "fig_results.pdf")
