#!/usr/bin/env python3
"""Aggregate the full-image re-scores into the paper's tables (mean ± std over seeds,
std with ddof=0 as in the earlier tables).

    python scripts/parallel/paper_tables.py   -> plans/paper-tables-full-image.md
"""
from __future__ import annotations
import json, statistics as st, time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "plans" / "paper-tables-full-image.md"
M = ["accuracy", "precision", "recall", "f1", "bleu", "rouge_l", "meteor", "cider"]
NAMES = ["Acc", "P", "R", "F1", "BLEU", "ROUGE", "METEOR", "CIDEr"]


def _eval(tag: str, split: str) -> dict | None:
    """eval_<split>.json of a job; a '-r2' re-run counts when the original never landed."""
    for t in (tag, tag + "-r2"):
        for kind in ("input_diag", "regen_full"):
            f = next((ROOT / "outputs" / kind / t).rglob(f"eval_{split}.json"), None) if (ROOT / "outputs" / kind / t).exists() else None
            if f:
                return json.loads(f.read_text())
    return None


def _agg(tags: list[str], split: str) -> dict | None:
    rows = [_eval(t, split) for t in tags]
    if any(r is None for r in rows):
        return None
    out = {k: (st.mean(100 * r[k] for r in rows), st.pstdev(100 * r[k] for r in rows)) for k in M}
    out["loss"] = (st.mean(r["loss"] for r in rows), st.pstdev(r["loss"] for r in rows))
    out["n_seeds"] = len(rows)
    return out


def _fmt(a: dict | None, keys=M) -> str:
    if a is None:
        return " | ".join("…" for _ in keys)
    return " | ".join(f"{a[k][0]:.2f} ± {a[k][1]:.2f}" for k in keys)


def main() -> None:
    mt_val = [f"mt-s{s}-t1-full" for s in (42, 123, 2026, 3407)]
    mt_test = [f"mt-s{s}" for s in (42, 123, 2026, 3407)]
    l1 = [f"l1ep-s{s}" for s in (42, 123, 3407)]
    l3_val = [f"l3ep-s{s}-t1-full" for s in (42, 123, 3407)]
    l3_test = [f"l3ep-s{s}" for s in (42, 123, 3407)]
    configs = [("bridge only (4 seeds)", mt_val, mt_test),
               ("+ LoRA, 1 epoch (3 seeds)", l1, l1),
               ("+ LoRA, 3 epochs (3 seeds)", l3_val, l3_test)]
    L = ["# Paper tables — full-image re-score (`--gen-image full`)", "",
         f"*Generated by `scripts/parallel/paper_tables.py` at {time.strftime('%Y-%m-%d %H:%M')}. ×100; "
         "mean ± std over seeds (ddof=0); CE not ×100. All metrics from `metrics.vqa_metrics.score_answers`.*", "",
         "## tab:main / tab:stability", "",
         "| Configuration | Split | " + " | ".join(NAMES) + " | CE |", "|---|---|" + "--:|" * 9]
    agg = {}
    for name, val_tags, test_tags in configs:
        for split, tags in (("val", val_tags), ("test", test_tags)):
            a = _agg(tags, split)
            agg[(name, split)] = a
            ce = f"{a['loss'][0]:.3f} ± {a['loss'][1]:.3f}" if a else "…"
            L.append(f"| {name} | {split} | {_fmt(a)} | {ce} |")
    base = agg[("bridge only (4 seeds)", "val")]
    L += ["", "## tab:levers (validation F1, Δ vs bridge only)", "",
          "| Intervention | F1 (3 seeds) | ΔF1 |", "|---|--:|--:|"]
    for name, t in [("random reference answer per epoch", "rq5-random"),
                    ("feature distillation", "rq5-feat"),
                    ("logit distillation, α = 0.1", "rq5-logit01"),
                    ("logit distillation, α = 1", "rq5-logit1")]:
        a = _agg([f"{t}-s{s}" for s in (42, 123, 3407)], "val")
        if a and base:
            L.append(f"| {name} | {a['f1'][0]:.2f} ± {a['f1'][1]:.2f} | {a['f1'][0] - base['f1'][0]:+.2f} |")
        else:
            L.append(f"| {name} | … | … |")
    for name in ("+ LoRA, 1 epoch (3 seeds)", "+ LoRA, 3 epochs (3 seeds)"):
        a = agg[(name, "val")]
        if a and base:
            L.append(f"| decoder LoRA r16, {name.split(', ')[1].split(' (')[0]} | {a['f1'][0]:.2f} ± {a['f1'][1]:.2f} | {a['f1'][0] - base['f1'][0]:+.2f} |")
    if base:
        L += ["", f"*Anchor: bridge only, val, 4 seeds: F1 {base['f1'][0]:.2f} ± {base['f1'][1]:.2f}. "
              "Full Q-Former row omitted: its training leaked the answer (fixed in 4a8eb6d; retrain pending).*"]
    L += ["", "## RQ3 — tiles × pooled input (Multi-Token, seed 42, val)", "",
          "| Input to the bridge | 1 tile | 3 tiles | 6 tiles |", "|---|--:|--:|--:|"]
    for name, tags in [("CLS (mean of per-tile CLS at T > 1)", ("mt-s42-t1-full", "mt-s42-t3-clsmean", "mt-s42-t6-clsmean")),
                       ("mean of every token (the old T > 1 path)", ("mt-s42-t1-full-mean", "mt-s42-t3-meanall", "mt-s42-t6-meanall"))]:
        cells = []
        for t in tags:
            d = _eval(t, "val")
            cells.append(f"{100 * d['f1']:.2f} (CE {d['loss']:.3f})" if d else "…")
        L.append(f"| {name} | " + " | ".join(cells) + " |")
    L += ["", "*F1 (val CE). On the 4:3 val images a 3-tile request tiles 1x1 and pads by repetition, so "
          "\"3 tiles\" is the whole image three times; 6 tiles = six 448px crops, no thumbnail.*"]
    OUT.write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
